name: webview_custom_interface_example
publish_to: "none"

environment:
  sdk: "^3.1.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
